package com.trentin.cerebrum;

import java.util.ArrayList;
import java.util.List;

public class BancoDeQuestoes {
    private static  List<ListaDeQuestoes> questoesDePortugues(){
        final List<ListaDeQuestoes> listaDeQuestoes = new ArrayList<>();

        // Criar objetos das listas de questões da classe e passar as questôes juntamente com opções e respostas
        final ListaDeQuestoes questao1 = new ListaDeQuestoes(R.drawable.livro,false,"Português","(UFG 2011) A enchente é um fenômeno do regime dos rios, que decorre do ciclo da água. No conto “O que veio de longe”, da obra Livro dos homens, de Ronaldo Correia de Brito, esse fenômeno é representado no processo composicional para", "caracterizar o trajeto do protagonista.", "vincular a narração a um espaço rural.", "demarcar a dimensão linear do enredo.", "refletir a estrutura narrativa da história.", "refletir a estrutura narrativa da história.","");
        final ListaDeQuestoes questao2 = new ListaDeQuestoes(R.drawable.livro,false,"Português","(UFG 2012) Em I-Juca-Pirama, de Gonçalves Dias, o andamento do enredo caracteriza uma obra híbrida entre o trágico e o épico porque","os episódios expressam uma divergência entre os ideais românticos e a cultura indígena.","as ações exprimem a fragilidade do prisioneiro e sua consequente punição, mas isso é superado por sua reação guerreira.","as atitudes do herói explicitam uma indecisão entre a morte honrada e o salvamento do pai.","os eventos narrados evidenciam o amor e a dedicação do prisioneiro ao pai, mas priorizam o sentimento tribal do guerreiro.","as ações exprimem a fragilidade do prisioneiro e sua consequente punição, mas isso é superado por sua reação guerreira.","");
        final ListaDeQuestoes questao3 = new ListaDeQuestoes(R.drawable.livro,false,"Português","Sobre os elementos narrativos que compõem os contos de Murilo Rubião, marque a alternativa correta:","O narrador que predomina é o de terceira pessoa. Sua narrativa demonstra uma onisciência dequem sabe toda a trajetória do personagem.","O desfecho do conto é sempre surpreendente, pois o insólito acaba desaparecendo, e a metamorfose do personagem se encerra.","O insólito substitui a realidade e até o final ela se mantém. Mas sua presença não dá possibilidade de redenção para os personagens.","O contraste entre o tempo linear e a mudança constante do espaço cria o absurdo na narrativa de Murilo Rubião.","O insólito substitui a realidade e até o final ela se mantém. Mas sua presença não dá possibilidade de redenção para os personagens.","");
        final ListaDeQuestoes questao4 = new ListaDeQuestoes(R.drawable.livro,false,"Português","Estão, entre os principais representantes do Orfismo, os seguintes escritores:","Miguel Torga e José Saramago.","Florbela Espanca e Almada Negreiros.","Fernando Pessoa e Mário de Sá-Carneiro.","José Régio e Eça de Queirós.","Fernando Pessoa e Mário de Sá-Carneiro.","");
        final ListaDeQuestoes questao5 = new ListaDeQuestoes(R.drawable.livro,false,"Português","A obra romanesca de José de Alencar introduziu na literatura brasileira quatro tipos de romances: indianista, histórico, urbano e regional. Desses quatro tipos, os que tiveram sua vida prolongada, de forma mais clara e intensa, até o Modernismo, ainda que modificados, foram:","Indianista e histórico","Histórico e urbano","Urbano e regional","Regional e indianista","Urbano e regional","");
        final ListaDeQuestoes questao6 = new ListaDeQuestoes(R.drawable.livro,false,"Português","(UFG 2012) Os gêneros textuais circulam no mundo com características próprias e exercem determinadas funções sociais, em conformidade com as quais os gêneros literários se transformam e se reconfiguram. Nesse sentido, em I-Juca-Pirama, de Gonçalves Dias, a função social do gênero épico de exaltar um povo ou retratá-lo em sua totalidade deixa de se realizar plenamente porque","o protagonista do poema, o prisioneiro Tupi, representa ideais ainda presentes no século XIX.","os escritores do século XIX já não se dedicam a longas narrativas em versos.","o tempo do poema, no enredo narrado, desenvolve ações em sentido linear.","os leitores do século XIX já não se sentem representados em narrativas heroicas.","os leitores do século XIX já não se sentem representados em narrativas heroicas.","");
        final ListaDeQuestoes questao7 = new ListaDeQuestoes(R.drawable.livro,false,"Português","(PUC-Campinas)Assinale a alternativa em que se encontram preocupações estéticas da Primeira Geração Modernista:","“Não entrem no verso culto o calão e solecismo, a sintaxe truncada, o metro cambaio, a indigência das imagens e do vocabulário do pensar e do dizer.”","“Vestir a Ideia de uma forma sensível que, entretanto, não terá seu fim em si mesma, mas que, servindo para exprimir a Ideia, dela se tornaria submissa.”","“Minhas reivindicações? Liberdade. Uso dela; não abuso.” “E não quero discípulos. Em arte: escola = imbecilidade de muitos para vaidade dum só.”","“Na exaustão causada pelo sentimentalismo, a alma ainda tremula e ressoante da febre do sangue, a alma que ama e canta porque sua vida é amor e canto, o que pode senão fazer o poema dos amores da vida real?”","“Minhas reivindicações? Liberdade. Uso dela; não abuso.” “E não quero discípulos. Em arte: escola = imbecilidade de muitos para vaidade dum só.”","");
        final ListaDeQuestoes questao8 = new ListaDeQuestoes(R.drawable.livro,false,"Português","Estão, entre as principais obras de Oswald de Andrade, exceto:","Losango Cáqui.","Serafim Ponte Grande.","Memórias: Um homem sem profissão.","Marco Zero: I - A revolução melancólica, II — Chão","Losango Cáqui.","");
        final ListaDeQuestoes questao9 = new ListaDeQuestoes(R.drawable.livro,false,"Português","(FAU-SP) O indianismo de nossos poetas românticos é:","uma forma de apresentar o índio em toda a sua realidade objetiva; o índio como elemento étnico da futura raça brasileira.","uma forma de apresentar o índio como motivo estético; idealização com simpatia e piedade; exaltação da bravura, do heroísmo e de todas as qualidades morais superiores.","um modelo francês seguido no Brasil; uma necessidade de exotismo que em nada difere do modelo europeu.","um meio de eternizar liricamente a aceitação, pelo índio, da nova civilização que se instalava."," uma forma de apresentar o índio como motivo estético; idealização com simpatia e piedade; exaltação da bravura, do heroísmo e de todas as qualidades morais superiores.","");
        final ListaDeQuestoes questao10 = new ListaDeQuestoes(R.drawable.livro,false,"Português","O gênero narrativo, na maioria das vezes, é expresso pela:","Poesia","Show","Romance","Jornal","Romance","");
        final ListaDeQuestoes questao11 = new ListaDeQuestoes(R.drawable.livro,false,"Português","O soneto é uma das formas mais tradicionais e, na maioria das vezes, tem conteúdo:","lírico","satírico","épico","cronístico","lírico","");
        final ListaDeQuestoes questao12 = new ListaDeQuestoes(R.drawable.livro,false,"Português","Assinale a afirmativa correta:","Aristóteles afirma que os textos épicos apresentam uma narrativa e sempre terão um narrador-personagem","A tragédia é um gênero literário","O gênero dramático apresenta esta estrutura: apresentação e desfecho","Os elementos essenciais de uma narrativa são: narrador, enredo, personagens, tempo e espaço","Os elementos essenciais de uma narrativa são: narrador, enredo, personagens, tempo e espaço","");
        final ListaDeQuestoes questao13 = new ListaDeQuestoes(R.drawable.questao13p,false,"Português","(Enem 2020 / Aplicação Digital)\nDe acordo com as intenções comunicativas e os recursos linguísticos que se destacam, determinadas funções são atribuídas à linguagem. A função que predomina nesse texto é a conativa, uma vez que ele","atua sobre o interlocutor, procurando convencê-lo a realizar sua escolha de maneira consciente.","coloca em evidência o canal de comunicação pelo uso das palavras “corrige” e “confirma”.","privilegia o texto verbal, de base informativa, em detrimento do texto não verbal.","usa a imagem como único recurso para interagir com o público a que se destina.","atua sobre o interlocutor, procurando convencê-lo a realizar sua escolha de maneira consciente.","");
        final ListaDeQuestoes questao14 = new ListaDeQuestoes(R.drawable.questao14p,false,"Português","O humor na charge é provocado porque a personagem comete um deslize referente a um dos fatores pragmáticos do texto, sendo ele:","a intencionalidade, considerando que o deslize cometido pela personagem foi proposital.","a informatividade, pois a personagem desconhece a figura de um pássaro, assim como desconhece o símbolo da rede social mencionada.","a situacionalidade, já que a situação comunicativa permite facilmente que um pássaro seja confundido com o símbolo de uma conhecida rede social.","a informatividade, uma vez que o humor decorre do fato de que ele não conhece o pássaro e faz referência ao símbolo do Twitter devido ao seu desconhecimento de mundo e conhecimento de mídias sociais.","a informatividade, uma vez que o humor decorre do fato de que ele não conhece o pássaro e faz referência ao símbolo do Twitter devido ao seu desconhecimento de mundo e conhecimento de mídias sociais.","");
        final ListaDeQuestoes questao15 = new ListaDeQuestoes(R.drawable.questao15p,false,"Português","Em sua conversa com o pai, Calvin busca persuadi-lo, recorrendo à estratégia argumentativa de:","mostrar que um bom trabalho como pai implica a valorização por parte do filho.","apelar para a necessidade que o pai demonstra de ser bem-visto pela família.","atribuir seu ponto de vista a terceiros para respaldar suas intenções.","explorar a preocupação do pai com a própria imagem e popularidade.","atribuir seu ponto de vista a terceiros para respaldar suas intenções.","");
        final ListaDeQuestoes questao16 = new ListaDeQuestoes(R.drawable.questao16p,false,"Português","Na tira, Mafalda e o pai compreendem a expressão “ano que vem” de maneiras distintas. É possível discriminar os diferentes pontos de vista na fala dos personagens à medida que:","Mafalda expressa sua dúvida em relação ao mundo adulto ao achar que não basta dizer “ano que vem”, é preciso comprovar que ele virá mesmo, enquanto seu pai apoia-se na consciência de que o tempo passa naturalmente.","o questionamento de Mafalda está baseado na recorrência de respostas inverídicas dadas pelos adultos como forma explícita de desviar-se de situações controversas.","a questão da forma como as crianças entendem a passagem do tempo está relacionada com as experiências reais já vividas, o que dificulta a construção de dimensões temporais que não sejam referentes a um tempo pretérito.","a expressão “ano que vem” refere-se abstratamente a um amplo acontecimento futuro e, por isso, Mafalda acredita ser provável a sua ocorrência. ","Mafalda expressa sua dúvida em relação ao mundo adulto ao achar que não basta dizer “ano que vem”, é preciso comprovar que ele virá mesmo, enquanto seu pai apoia-se na consciência de que o tempo passa naturalmente.","");
        final ListaDeQuestoes questao17 = new ListaDeQuestoes(R.drawable.questao17p,false,"Português","Esse infográfico revela que o BNDES se mobilizará em prol do cumprimento de um dos objetivos da Agenda 2030 da ONU: a universalização do saneamento básico. A leitura dessa representação visual de informações permite afirmar corretamente que, para essa meta ser atingida, é indispensável que:","a disponibilidade e a gestão sustentável de água e esgoto sejam ampliadas progressivamente em todos os estados brasileiros. ","os investimentos em saneamento básico sejam ampliados para que a meta do Plano Nacional de Saneamento Básico seja cumprida até 2030.","as pessoas desprovidas de água tratada e saneamento, de maneira geral, envolvam-se em projetos estruturados pelo BNDES.","o investimento em sistemas de abastecimento de água seja priorizado em relação à ampliação do esgotamento sanitário.","a disponibilidade e a gestão sustentável de água e esgoto sejam ampliadas progressivamente em todos os estados brasileiros. ","");
        final ListaDeQuestoes questao18 = new ListaDeQuestoes(R.drawable.questao18p,false,"Português","A internet proporcionou o surgimento de novos paradigmas sociais e impulsionou a modificação de outros já estabelecidos nas esferas da comunicação e da informação. A principal consequência criticada na tirinha sobre esse processo é a:","comercialização de pontos de vista.","criação de memes.","ampliação da blogosfera.","supremacia das ideias cibernéticas.","comercialização de pontos de vista.","");
        final ListaDeQuestoes questao19 = new ListaDeQuestoes(R.drawable.questao19p,false,"Português","Importantes recursos de reflexão e crítica próprios do gênero textual, esses quadrinhos possibilitam pensar sobre o papel da tecnologia nas sociedades contemporâneas, pois:","indicam a solidão existencial dos usuários das redes sociais virtuais.","criticam a superficialidade das relações humanas mantidas pela internet.","retratam a dificuldade de adaptação de pessoas mais velhas às relações virtuais.","ironizam o crescimento da conexão virtual oposto à falta de vínculos reais entre as pessoas.","ironizam o crescimento da conexão virtual oposto à falta de vínculos reais entre as pessoas.","");
        final ListaDeQuestoes questao20 = new ListaDeQuestoes(R.drawable.questao20p,false,"Português","Nesse texto, o entrelaçamento de vários gêneros textuais é um mecanismo discursivo para","destacar a fidelidade dos cães.","realçar as vantagens de se adotar um cão.","mostrar a dependência decorrente do amor aos cães.","enfatizar o interesse das pessoas pela adoção de cães.","mostrar a dependência decorrente do amor aos cães.","");

        // add todas as questôes para List<ListaDeQuestoes>
        listaDeQuestoes.add(questao1);
        listaDeQuestoes.add(questao2);
        listaDeQuestoes.add(questao3);
        listaDeQuestoes.add(questao4);
        listaDeQuestoes.add(questao5);
        listaDeQuestoes.add(questao6);
        listaDeQuestoes.add(questao7);
        listaDeQuestoes.add(questao8);
        listaDeQuestoes.add(questao9);
        listaDeQuestoes.add(questao10);
        listaDeQuestoes.add(questao11);
        listaDeQuestoes.add(questao12);
        listaDeQuestoes.add(questao13);
        listaDeQuestoes.add(questao14);
        listaDeQuestoes.add(questao15);
        listaDeQuestoes.add(questao16);
        listaDeQuestoes.add(questao17);
        listaDeQuestoes.add(questao18);
        listaDeQuestoes.add(questao19);
        listaDeQuestoes.add(questao20);
        return listaDeQuestoes;
    }
    private static List<ListaDeQuestoes> questoesDeMatematica(){
        final List<ListaDeQuestoes> listaDeQuestoes = new ArrayList<>();

        // Criar objetos das listas de questões da classe e passar as questôes juntamente com opções e respostas
        final ListaDeQuestoes questao1 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","(Fuvest) Ao cobrar uma falta em um jogo de futebol, um jogador imprime à bola uma velocidade de 43,2 km/h. Sabendo que a bola gasta 3 s até atingir as redes, determine a distância percorrida.","36 m","48 m","52 m","28 m","36 m","");
        final ListaDeQuestoes questao2 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","(Enem 2020 Digital) Uma associação desportiva contratou uma empresa especializada para construir um campo de futebol, em formato retangular, com 250 metros de perímetro. Foi elaborada uma planta para esse campo na escala 1 : 2 000. Na planta, a medida do perímetro do campo de futebol, em metro, é:", "0,0005","0,125", "8","250", "8","");
        final ListaDeQuestoes questao3 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","(FGV) Sejam os números 7, 8, 3, 5, 9 e 5 seis números de uma lista de nove números inteiros. O maior valor possível para a mediana dos nove números da lista é","5","6","7","8","8","");
        final ListaDeQuestoes questao4 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","(Fundatec) Se a mediana de um determinado processo for igual a 7, isso quer dizer que:","O 7º valor da amostra representará a mediana.","O 7º valor da amostra ordenada representará a mediana.","A posição mediana é 7.","50% dos valores da amostra são iguais a 7.","50% dos valores da amostra são iguais a 7.","");
        final ListaDeQuestoes questao5 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","(IF-CE 2020) Um relógio A bate a cada 15 minutos, outro relógio B bate a cada 20 minutos, e um terceiro relógio C, a cada 25 minutos. O menor intervalo de tempo decorrido entre duas batidas simultâneas dos três relógios, em horas, é igual a:","3","6","4","5","5","");
        final ListaDeQuestoes questao6 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","(Enem) João tem uma loja onde fabrica e vende moedas de chocolate com diâmetro de 4 cm e preço de R$ 1,50 a unidade. Pedro vai a essa loja e, após comer várias moedas de chocolate, sugere ao João que ele faça moedas com 8 cm de diâmetro e mesma espessura e cobre R$ 3 a unidade. Considerando que o preço da moeda depende apenas da quantidade de chocolate, João","aceita a proposta de Pedro, pois, se dobra o diâmetro, o preço também deve dobrar","rejeita a proposta de Pedro, pois o preço correto seria R$ 12","rejeita a proposta de Pedro, pois o preço correto seria R$ 6","rejeita a proposta de Pedro, pois o preço correto seria R$ 4,50","rejeita a proposta de Pedro, pois o preço correto seria R$ 6","");
        final ListaDeQuestoes questao7 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","(Enem 2016 - PPL) Tradicionalmente uma pizza média de formato circular tem diâmetro de 30 cm e é dividida em 8 fatias iguais (mesma área). Uma família, ao se reunir para o jantar, fará uma pizza de formato circular e pretende dividi-la em 10 fatias também iguais. Entretanto, eles desejam que cada fatia dessa pizza tenha o mesmo tamanho (mesma área) de cada fatia da pizza média quando dividida em 8 fatias iguais. Qual o valor mais próximo do raio com que deve ser feita a pizza, em centímetros, para que eles consigam dividi-la da forma pretendida?","18,75","16,50","33","37,50","16,50","");
        final ListaDeQuestoes questao8 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","(Enem - PPL) Uma escola tem um terreno vazio no formato retangular cujo perímetro é 40 m, onde se pretende realizar uma única construção que aproveite o máximo de área possível. Após a análise realizada por um engenheiro, este concluiu que, para atingir o máximo de área do terreno com uma única construção, a obra ideal seria","um pátio com 100 m²","um banheiro com 8 m²","uma sala de aula com 16 m²","um auditório com 36 m²","um pátio com 100 m²","");
        final ListaDeQuestoes questao9 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","(Enem) O prefeito de uma cidade deseja promover uma festa popular no parque municipal para comemorar o aniversário de fundação do município. Sabe-se que esse parque possui formato retangular, com 120 m de comprimento por 150 m de largura. Além disso, para segurança das pessoas presentes no local, a polícia recomenda que a densidade média, num evento dessa natureza, não supere quatro pessoas por metro quadrado. Seguindo as recomendações de segurança estabelecidas pela polícia, qual é o número máximo de pessoas que poderão estar presentes na festa?","72.000","4500","1000","18.000","72.000","");
        final ListaDeQuestoes questao10 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","(UEAAM) Uma pequena empresa que fabrica camisetas verificou que o lucro obtido com a venda de seus produtos obedece à função L(x) = 75x – 3000, sendo L(x) o lucro em reais e x o número de camisetas vendidas, para 40 < x ≤ 120. Para que o lucro da empresa chegue a R$ 4.000,00, o menor número de camisetas a serem vendidas é:","92","94","95","93","94","");
        final ListaDeQuestoes questao11 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","Uma fábrica de panelas opera com um custo fixo mensal de R$ 9 800,00 e um custo variável por panela de R$ 45,00. Cada panela é vendida por R$ 65,00. Seja x a quantidade que deve ser produzida e vendida mensalmente para que o lucro mensal seja igual a 20% da receita. A soma dos algarismos de x é:","2","3","5","4","5","");
        final ListaDeQuestoes questao12 = new ListaDeQuestoes(R.drawable.mate,false,"Matemática","(Enem 2019) Uma empresa tem diversos funcionários. Um deles é o gerente, que recebe R$ 1 000,00 por semana. Os outros funcionários são diaristas. Cada um deles trabalha 2 dias por semana, recebendo R$ 80,00 por dia trabalhado. Chamando de X a quantidade total de funcionários da empresa, a quantia Y, em reais, que esta empresa gasta semanalmente para pagar seus funcionários é expressa por:","Y = 160X + 1 000","Y = 80X + 1 000","Y = 80X + 1 080","Y = 160X + 840","Y = 160X + 840","");
        final ListaDeQuestoes questao13 = new ListaDeQuestoes(R.drawable.questao13m,false,"Matemática","(Enem 2016)  Um senhor, pai de dois filhos, deseja comprar dois terrenos, com áreas de mesma medida, um para cada filho. Um dos terrenos visitados já está demarcado e, embora não tenha um formato convencional (como se observa na Figura B), agradou ao filho mais velho e, por isso, foi comprado. O filho mais novo possui um projeto arquitetônico de uma casa que quer construir, mas, para isso, precisa de um terreno na forma retangular (como mostrado na Figura A) cujo comprimento seja  7 m  maior do que a largura.Para satisfazer o filho mais novo, esse senhor precisa encontrar um terreno retangular cujas medidas, em metro, do comprimento e da largura sejam iguais, respectivamente, a","7,5 e 14,5.","9,0 e 16,0.","9,39,3 e 16,3.","10,0 e 17,0.","9,0 e 16,0.","");
        final ListaDeQuestoes questao14 = new ListaDeQuestoes(R.drawable.questao14m,false,"Matemática","Se a área do círculo inscrito no hexágono é 3π metros quadrados, então a área do hexágono, em metro quadrado, é: ","9","6√3","9√2","12","6√3","");
        final ListaDeQuestoes questao15 = new ListaDeQuestoes(R.drawable.questao15m,false,"Matemática","Qual é a medida da área pintada, em metros quadrados, do triângulo DEF sabendo que o triangulo é equilátero de lado igual a 1 metro?","1/16","√3/16","1/8","√3/8","√3/16","");
        final ListaDeQuestoes questao16 = new ListaDeQuestoes(R.drawable.questao16m,false,"Matemática","Wilson tem um terreno retangular e desejando plantar uma horta, colocou dois irrigadores nesse terreno, ambos com alcance circular de raio igual a 4 metros, como na figura.A área que os irrigadores não alcançam será uma parte do terreno em que Wilson não fará a horta. Qual o valor dessa área? Utilize π = 3,14.","100,48 m²","36,48 m²","102,88 m²","27,52 m²","27,52 m²","");
        final ListaDeQuestoes questao17 = new ListaDeQuestoes(R.drawable.questao17m,false,"Matemática","O banheiro de uma escola pública, com paredes e piso em formato retangular, medindo 5 metros de largura, 4 metros de comprimento e 3 metros de altura, precisa de revestimento no piso e nas paredes internas, excluindo a área da porta, que mede 1 metro de largura por 2 metros de altura. Após uma tomada de preços com cinco fornecedores, foram verificadas as seguintes combinações de azulejos para as paredes e de lajotas para o piso, com os preços dados em reais por metro quadrado, conforme a tabela.Desejando-se efetuar a menor despesa total, deverá ser escolhido o fornecedor:","A","B","C","D","D","");
        final ListaDeQuestoes questao18 = new ListaDeQuestoes(R.drawable.questao18m,false,"Matemática","A área de lazer da fazenda da Dona Helena tem o formato retangular com 15 m de comprimento e 12 m de largura. Existe uma piscina de adulto e uma infantil com o formato circular de raios 3 m e 2 m respectivamente. Helena pretende pintar o chão de toda a área de lazer no tom de verde. Um galão de tinta é recomendável para pintar 11 m². Quantos galões de tinta Dona Helena deve comprar para pintar a área desejada sabendo que as piscinas não serão pintadas? (Dado π = 3)","14 galões","13 galões","12 galões","11 galões","13 galões","");
        final ListaDeQuestoes questao19 = new ListaDeQuestoes(R.drawable.questao19m,false,"Matemática","Em um mês, uma loja de eletrônicos começa a obter lucro já na primeira semana. O gráfico representa o lucro (L) dessa loja desde o início do mês até o dia 20. Mas esse comportamento se estende até o último dia, o dia 30.A representação algébrica do lucro (L) em função do tempo (t) é:","L(t) = 20t + 3 000","L(t) = 20t + 4 000","L(t) = 200t","L(t) = 200t – 1 000","L(t) = 200t – 1 000","");
        final ListaDeQuestoes questao20 = new ListaDeQuestoes(R.drawable.questao20m,false,"Matemática","Um sítio foi adquirido por R$ 200 000,00. O proprietário verificou que a valorização do imóvel, após sua aquisição, cresceu em função do tempo conforme o gráfico, e que essa tendência de valorização se manteve nos anos seguintes.O valor desse sítio, no décimo ano após sua compra, em real, será de:","190 000","232 000","272 000","400 000","400 000","");


        // add todas as questôes para List<ListaDeQuestoes>
        listaDeQuestoes.add(questao1);
        listaDeQuestoes.add(questao2);
        listaDeQuestoes.add(questao3);
        listaDeQuestoes.add(questao4);
        listaDeQuestoes.add(questao5);
        listaDeQuestoes.add(questao6);
        listaDeQuestoes.add(questao7);
        listaDeQuestoes.add(questao8);
        listaDeQuestoes.add(questao9);
        listaDeQuestoes.add(questao10);
        listaDeQuestoes.add(questao11);
        listaDeQuestoes.add(questao12);
        listaDeQuestoes.add(questao13);
        listaDeQuestoes.add(questao14);
        listaDeQuestoes.add(questao15);
        listaDeQuestoes.add(questao16);
        listaDeQuestoes.add(questao17);
        listaDeQuestoes.add(questao18);
        listaDeQuestoes.add(questao19);
        listaDeQuestoes.add(questao20);

        return listaDeQuestoes;
    }
    private static List<ListaDeQuestoes> questoesDeQuimica(){
        final List<ListaDeQuestoes> listaDeQuestoes = new ArrayList<>();

        // Criar objetos das listas de questões da classe e passar as questôes juntamente com opções e respostas
        final ListaDeQuestoes questao1 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","(Unesp 2021) As bacteriorrizas são exemplos de associações simbióticas entre bactérias e raízes de plantas leguminosas. Essas bactérias fixam o nitrogênio atmosférico (N2), transformando-o em amônia (NH3). Nessa transformação, o número de oxidação do elemento nitrogênio é alterado de:","+2 para –3, sendo reduzido.","+2 para +1, sendo reduzido.","0 para +3, sendo oxidado."," 0 para –3, sendo reduzido."," 0 para –3, sendo reduzido.","");
        final ListaDeQuestoes questao2 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","As chuvas ácidas podem ter diferentes composições dependendo do local onde são formadas, as mais nocivas são formadas em grandes centros industriais, onde há queima de combustíveis fósseis (gasolina, óleo diesel). Esse tipo de chuva é carregado de poluentes, marque a opção que traz os compostos que a torna nociva à saúde.","óxidos de carbono (CO, CO2)","óxidos de cálcio (CaO, CaO2)","óxidos de enxofre (SO2, SO3)","óxidos de nitrogênio (NO, NO2)","óxidos de enxofre (SO2, SO3)","");
        final ListaDeQuestoes questao3 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","Quantos elétrons de valência existem na configuração do elemento químico de número atômico 83?","2","3","4","5","5","");
        final ListaDeQuestoes questao4 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","Qual dos números atômicos a seguir corresponde a um elemento químico que apresenta em sua camada de valência 3 elétrons?","55", "32","49","17","49","");
        final ListaDeQuestoes questao5 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","(UEFS-BA) O titânio é um metal utilizado na fabricação de motores de avião e pinos para prótese. Quantos elétrons há no último nível da configuração eletrônica desse metal? Dado: Ti (Z =22).","4","3","2","1","2","");
        final ListaDeQuestoes questao6 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","(Puccamp - SP) Considere as seguintes equações termoquímicas:\n" + "I. 3 O2(g) → 2 O3(g) ∆H1 = +284,6 kJ\n" + "II. 1 C(grafita) + 1 O2(g)→ 1 CO2(g) ∆H2 = -393,3 kJ\n" + "III. 1 C2H4(g) + 3 O2(g) → 2 CO2(g) + 2H2O(l) ∆H3 = -1410,8 kJ\n" + "IV. 1 C3H6(g) + 1 H2(g) → 1 C3HO8(g) ∆H4 = -123,8 kJ\n" + "V. 1 I(g) → 1/2 I2(g) ∆H5 = -104,6 kJ\n" + "Qual é a variação de entalpia que pode ser designada calor de formação ou calor de combustão?","∆H3","∆H1","∆H2","∆H4","∆H2","");
        final ListaDeQuestoes questao7 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","(PUC-MG) Sejam dadas as equações termoquímicas, todas a 25 ºC e 1 atm:\n" + "\n" + "I- H2(g)+ ½ O2(g) →H2O(l) ∆H = -68,3 Kcal/mol\n" + "II- 2Fe(s)+ 3/2 O2(g)→Fe2O3(s) ∆H = -196,5 Kcal/mol\n" + "III- 2Al(s)+ 3/2 O2(g)→Al2O3(s) ∆H = -399,1 Kcal/mol\n" + "IV - C(grafite)+ O2(g)→ CO2(g) ∆H = -94,0 Kcal/mol\n" + "Exclusivamente sob o ponto de vista energético, das reações acima, a que você escolheria como fonte de energia é:","I","III","II","IV","III","");
        final ListaDeQuestoes questao8 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","Maria usou um livro de receitas para fazer um bolo de fubá. Mas, ao fazer a tradução do livro do inglês para o português, a temperatura permaneceu em Fahrenheit (ºF). A receita disse que o bolo deve ser levado ao forno a 392 ºF e permanecer nessa temperatura por 30 minutos. Qual é a temperatura em graus Celsius que Maria deve deixar o forno para não errar a receita?","100ºc","200ºc","150ºc","250ºc","200ºc","");
        final ListaDeQuestoes questao9 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","A preocupação com o efeito estufa tem sido cada vez mais notada. Em alguns dias do verão de 2009, a temperatura na cidade de São Paulo chegou a atingir 34 ºC. O valor dessa temperatura em escala Kelvin é:","239,15","307,15","273,15","– 307,15","307,15","");
        final ListaDeQuestoes questao10 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","Lorde Kelvin verificou experimentalmente que, quando um gás é resfriado de 0 ºC para -1 ºC, por exemplo, ele perde uma fração de sua pressão igual a 1/273,15. Raciocinou então que na temperatura de -273,15 ºC a pressão do gás se tornaria nula, ou seja, a energia cinética das partículas do gás seria igual a zero. Kelvin denominou a temperatura de -273,15 ºC de zero absoluto.\n" + "\n" + "Identifique a alternativa em que a conversão de unidades é incorreta:","0 ºC é igual a 273,15 K","-100 ºC é igual a 173,15 K","26,85 K é igual a 300 ºC","500 k é igual a 226,85 ºC","26,85 K é igual a 300 ºC","");
        final ListaDeQuestoes questao11 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","(ITA-SP) Para medir a febre de pacientes, um estudante de medicina criou sua própria escala linear de temperaturas. Nessa nova escala, os valores de O (zero) e 10 (dez) correspondem, respectivamente, a 37°C e 40°C. A temperatura de mesmo valor numérico em ambas as escalas é aproximadamente:","52,9 ºC","28,5 ºC","74,3 ºC","- 8,5 ºC","52,9 ºC","");
        final ListaDeQuestoes questao12 = new ListaDeQuestoes(R.drawable.quimica,false,"Química","(MACK-SP) O vinagre usado para temperar saladas é uma mistura, em proporções adequadas, de:","Ácido etanoico (ácido acético) e água","Ácido etanoico e etanal","Etanol e água","Etanol e cloreto de sódio","Ácido etanoico (ácido acético) e água","");
        final ListaDeQuestoes questao13 = new ListaDeQuestoes(R.drawable.questao13q,false,"Química","A aplicação excessiva de fertilizantes nitrogenados na agricultura pode acarretar alterações no solo e na água pelo acúmulo de compostos nitrogenados, principalmente a forma mais oxidada, favorecendo a proliferação de algas e plantas aquáticas e alterando o ciclo do nitrogênio, representado no esquema. A espécie nitrogenada mais oxidada tem sua quantidade controlada por ação de microrganismos que promovem a reação de redução dessa espécie, no processo denominado desnitrificação.O processo citado está representado na etapa:","II","III","IV","V","V","");
        final ListaDeQuestoes questao14 = new ListaDeQuestoes(R.drawable.questao14q,false,"Química","As células e os organismos precisam realizar trabalho para permanecerem vivos e se reproduzirem. A energia metabólica necessária para a realização desse trabalho é oriunda da oxidação de combustíveis, gerados no ciclo do carbono, por meio de processos capazes de interconverter diferentes formas da energia. Nesse ciclo, a formação de combustíveis está vinculada à conversão de energia:","eletromagnética em química.","cinética em eletromagnética.","química em térmica.","eletroquímica em calor.","eletromagnética em química.","");
        final ListaDeQuestoes questao15 = new ListaDeQuestoes(R.drawable.questao15q,false,"Química","A corrosão é um processo eletroquímico e, no caso do ferro, ocorre a precipitação do óxido de ferro (III) hidratado, substância marrom pouco solúvel, conhecida como ferrugem. Esse processo corrosivo é, de maneira geral, representado pela equação química: Uma forma de impedir o processo corrosivo nesses utensílios é","renovar sua superfície, polindo-a semanalmente.","evitar o contato do utensílio com o calor, isolando-o termicamente.","impermeabilizar a superfície, isolando-a de seu contato com o ar úmido.","esterilizar frequentemente os utensílios, impedindo a proliferação de bactérias.","impermeabilizar a superfície, isolando-a de seu contato com o ar úmido.","");
        final ListaDeQuestoes questao16 = new ListaDeQuestoes(R.drawable.questao16q,false,"Química","O elemento ferro é essencial em nossa alimentação, pois ajuda a prevenir doenças como a anemia. Normalmente, na alimentação é ingerido na forma de Fe3+, sendo necessário o uso de agentes auxiliares de absorção, como o ácido ascórbico (vitamina C), cuja ação pode ser representada pelo esquema reacional a seguir. A ação do ácido ascórbico ocorre por meio de uma reação de:","eliminação","substituição","oxirredução","neutralização","oxirredução","");
        final ListaDeQuestoes questao17 = new ListaDeQuestoes(R.drawable.questao17q,false,"Química","Atualmente, soldados em campo, seja em treinamento ou em combate, podem aquecer suas refeições, prontas e embaladas em bolsas plásticas, utilizando aquecedores químicos, sem precisar fazer fogo. Dentro dessas bolsas existe magnésio metálico em pó e, quando o soldado quer aquecer a comida, ele coloca água dentro da bolsa, promovendo a reação descrita pela equação química:O aquecimento dentro da bolsa ocorre por causa da:","redução sofrida pelo oxigênio, que é uma reação exotérmica.","oxidação sofrida pelo magnésio, que é uma reação exotérmica.","oxidação sofrida pelo hidrogênio, que é uma reação exotérmica.","redução sofrida pelo magnésio, que é uma reação endotérmica.","oxidação sofrida pelo magnésio, que é uma reação exotérmica.","");
        final ListaDeQuestoes questao18 = new ListaDeQuestoes(R.drawable.questao18q,false,"Química","O gráfico a seguir representa a curva de resfriamento da água pura à pressão constante de 1 atm. Marque a Verdadeira:","O fenômeno que ocorre na região B da curva é a solidificação e há duas fases em equilíbrio.","Nas regiões B e D da curva, a temperatura permanece constante.","Na região C da curva, há somente a fase sólida.","Na região D da curva,não coexistem as fases sólida e líquida.","Nas regiões B e D da curva, a temperatura permanece constante.","");
        final ListaDeQuestoes questao19 = new ListaDeQuestoes(R.drawable.questao19q,false,"Química","O ponto de fusão, o ponto de ebulição e o tempo durante o qual a substância permanece no estado líquido são, respectivamente:","150, 65 e 5","65, 150 e 25","150, 65 e 25","65, 150 e 5","65, 150 e 5","");
        final ListaDeQuestoes questao20 = new ListaDeQuestoes(R.drawable.questao20q,false,"Química","O ácido tartárico, um constituinte das uvas, possui a estrutura abaixo:Substituindo em sua molécula cada um dos grupos carboxila (COOH) por um grupo metil, obtém-se:","diol","aldeído","diácido","tetrol","diol","");


        // add todas as questôes para List<ListaDeQuestoes>
        listaDeQuestoes.add(questao1);
        listaDeQuestoes.add(questao2);
        listaDeQuestoes.add(questao3);
        listaDeQuestoes.add(questao4);
        listaDeQuestoes.add(questao5);
        listaDeQuestoes.add(questao6);
        listaDeQuestoes.add(questao7);
        listaDeQuestoes.add(questao8);
        listaDeQuestoes.add(questao9);
        listaDeQuestoes.add(questao10);
        listaDeQuestoes.add(questao11);
        listaDeQuestoes.add(questao12);
        listaDeQuestoes.add(questao13);
        listaDeQuestoes.add(questao14);
        listaDeQuestoes.add(questao15);
        listaDeQuestoes.add(questao16);
        listaDeQuestoes.add(questao17);
        listaDeQuestoes.add(questao18);
        listaDeQuestoes.add(questao19);
        listaDeQuestoes.add(questao20);

        return listaDeQuestoes;
    }
    private static List<ListaDeQuestoes> questoesDeGeografia(){
        final List<ListaDeQuestoes> listaDeQuestoes = new ArrayList<>();

        // Criar objetos das listas de questões da classe e passar as questôes juntamente com opções e respostas
        final ListaDeQuestoes questao1 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","(Unitau) Suponha um país com uma pirâmide etária de base larga e topo afunilado, assemelhando-se a um triângulo, apresentando sete a oito camadas de crescimento populacional. Sobre esse país, é possível afirmar que:","apresenta uma alta expectativa de vida.","apresenta uma alta taxa de natalidade.","apresenta uma alta taxa de mortalidade infantil.","essa pirâmide é típica de países desenvolvidos.","apresenta uma alta taxa de natalidade.","");
        final ListaDeQuestoes questao2 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","Quais são os dois oceanos que banham a América do Sul na porção leste e oeste?","Pacífico e Índico.","Atlântico e Pacífico","Mediterrâneo e Pacífico.","Atlântico e Mediterrâneo.","Atlântico e Pacífico","");
        final ListaDeQuestoes questao3 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","(Enem) Considerando a riqueza dos recursos hídricos brasileiros, uma grave crise de água em nosso país poderia ser motivada por:","reduzida área de solos agricultáveis.","ausência de reservas de águas subterrâneas.","escassez de rios e de grandes bacias hidrográficas.","degradação dos mananciais e desperdício no consumo.","degradação dos mananciais e desperdício no consumo.","");
        final ListaDeQuestoes questao4 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","A América do Sul é um subcontinente localizado na porção mais austral da América. Ao longo da sua extensão latitudinal, ela é cortada pelas seguintes linhas imaginárias:","Linha do Equador e Trópico de Capricórnio.","Trópico de Câncer e Círculo Polar Ártico.","Meridiano de Greenwich e Trópico de Capricórnio.","Trópico de Capricórnio e Trópico de Câncer.","Linha do Equador e Trópico de Capricórnio.","");
        final ListaDeQuestoes questao5 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","O Brasil é o maior país em extensão territorial da América do Sul. Ele faz fronteiras com 10 países da América do Sul, com exceção de","Bolívia e Peru.","Guiana e Chile.","Chile e Equador.","Equador e Guiana.","Chile e Equador.","");
        final ListaDeQuestoes questao6 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","(Enem) O bônus demográfico é caracterizado pelo período em que, por causa da redução do número de filhos por mulher, a estrutura populacional fica favorável ao crescimento econômico. Isso acontece porque há proporcionalmente menos crianças na população, e o percentual de idosos ainda não é alto.\n" + "\n" + "GOIS, A. O Globo, 5 abr. 2015 (adaptado).\n" + "\n" + "A ação estatal que contribui para o aproveitamento do bônus demográfico é o estímulo à:","atração de imigrantes","elevação da carga tributária","qualificação da mão de obra","admissão de exilados políticos","qualificação da mão de obra","");
        final ListaDeQuestoes questao7 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","(Enem) Os países industriais adotaram uma concepção diferente das relações familiares e do lugar da fecundidade na vida familiar e social. A preocupação de garantir uma transmissão integral das vantagens econômicas e sociais adquiridas tem como resultado uma ação voluntária de limitação do número de nascimentos\n" + "\n" + "GEORGE, P. Panorama do mundo atual. São Paulo: Difusão Europeia do Livro, 1968 (adaptado).\n" + "\n" + "Em meados do século XX, o fenômeno social descrito contribuiu para o processo europeu de:","estabilização da pirâmide etária","conclusão da transição demográfica","contenção da entrada de imigrantes","elevação do crescimento vegetativo","conclusão da transição demográfica","");
        final ListaDeQuestoes questao8 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","(Unitau) Suponha um país com uma pirâmide etária de base larga e topo afunilado, assemelhando-se a um triângulo, apresentando sete a oito camadas de crescimento populacional. Sobre esse país, é possível afirmar que:","apresenta uma alta expectativa de vida","apresenta uma alta taxa de mortalidade infantil","essa pirâmide é típica de países desenvolvidos","apresenta uma alta taxa de natalidade","apresenta uma alta taxa de natalidade","");
        final ListaDeQuestoes questao9 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","(Enem) A redução do valor da aposentadoria se deve ao fator previdenciário, mecanismo utilizado pelo INSS para tentar adiar a aposentadoria dos trabalhadores mais jovens, penalizando quem se aposenta mais cedo, já que esse segurado, teoricamente, vai receber o benefício por mais tempo.\n" + "\n" + "RESENDE, T. Disponível em: http://ieprev.com.br. Acesso em: 25 out. 2015 (adaptado).\n" + "\n" + "Políticas previdenciárias como a apresentada no texto têm sido justificadas com base na dinâmica populacional de aumento da:","fuga de cérebros","taxa de natalidade","expectativa de vida","proporção de adultos","expectativa de vida","");
        final ListaDeQuestoes questao10 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","A urbanização e a expansão na rede de saneamento básico são realidades que marcaram o Brasil ao longo do século XX. Mudanças no padrão econômico do país e necessidades sanitárias justificaram a ocorrência desses elementos que influenciam diretamente no comportamento da população, como na:","natalidade","população ativa","escolaridade","expectativa de vida","expectativa de vida","");
        final ListaDeQuestoes questao11 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","Com extensão territorial de 735.612 quilômetros quadrados, a América Central possui 193,3 milhões de habitantes, sendo a densidade demográfica de 106,4 habitantes por quilômetro quadrado. Marque a alternativa que indica o país mais populoso da América Central.","Guatemala","Costa Rica","Cuba","México","Guatemala","");
        final ListaDeQuestoes questao12 = new ListaDeQuestoes(R.drawable.geografia,false,"Geografia","O Brasil é o maior país em extensão territorial da América do Sul. Ele faz fronteiras com 10 países da América do Sul, com exceção de","Bolívia e Peru","Guiana e Chile","Chile e Equador","Argentina e Peru","Chile e Equador","");
        final ListaDeQuestoes questao13 = new ListaDeQuestoes(R.drawable.questao13g,false,"Geografica","Uma consequência socioeconômica para os países que vivenciam o fenômeno demográfico ilustrado é a diminuição da:","despesa de natureza previdenciária.","disponibilidade de serviços de saúde.","média de expectativa de vida.","oferta de mão de obra nacional.","oferta de mão de obra nacional.","");
        final ListaDeQuestoes questao14 = new ListaDeQuestoes(R.drawable.questao14g,false,"Geografica","Com base nas pirâmides etárias apresentadas, é correto afirmar que:","o país 1 é subdesenvolvido, haja vista o elevado número de jovens.","o país 2 é desenvolvido, haja vista o elevado número de idosos.","o país 1 é desenvolvido, haja vista o predomínio de população adulta.","o país 2 é subdesenvolvido, haja vista a menor taxa de natalidade.","o país 1 é desenvolvido, haja vista o predomínio de população adulta.","");
        final ListaDeQuestoes questao15 = new ListaDeQuestoes(R.drawable.questao15g,false,"Geografica","A evolução da pirâmide etária apresentada indica a seguinte tendência:","expansão do índice de mortalidade.","aumento da expectativa de vida.","crescimento da faixa juvenil.","elevação da taxa de fecundidade.","aumento da expectativa de vida.","");
        final ListaDeQuestoes questao16 = new ListaDeQuestoes(R.drawable.questao16g,false,"Geografica","Taxa média de crescimento anual da população brasileira.A alteração apresentada no gráfico a partir da década de 1960 é reflexo da redução do seguinte indicador populacional:","população absoluta.","índice de mortalidade.","desigualdade social.","taxa de fecundidade.","taxa de fecundidade.","");
        final ListaDeQuestoes questao17 = new ListaDeQuestoes(R.drawable.questao17g,false,"Geografica","Existem diferentes tipos de movimentos entre placas tectônicas. Considerando a Falha de San Andreas, classifique o tipo de movimento realizado pelas placas que a compõem e o principal evento geológico a ele associado.","divergente; a ativação do processo plutônico;","conservativo; a ocorrência de terremotos;","construtivo; a formação de cadeias montanhosas;","destrutivo; a formação de fossas oceânicas;","conservativo; a ocorrência de terremotos;","");
        final ListaDeQuestoes questao18 = new ListaDeQuestoes(R.drawable.questao18g,false,"Geografica","A tirinha acima considera que a Organização das Nações Unidas:","apresenta uma baixa visibilidade para proferir discursos de paz.","possui um baixo poder de convencimento sobre as decisões do Vaticano.","não possui um amplo reconhecimento diplomático internacional.","é ineficiente em seu objetivo de conter conflitos internacionais.","é ineficiente em seu objetivo de conter conflitos internacionais.","");
        final ListaDeQuestoes questao19 = new ListaDeQuestoes(R.drawable.questao19g,false,"Geografica","Na charge, há uma crítica ao processo produtivo agrícola brasileiro relacionada ao","aumento da demanda por produtos naturais.","crescimento da produção de alimentos.","hábito de adquirir derivados industriais.","uso de agrotóxicos nas plantações.","uso de agrotóxicos nas plantações.","");
        final ListaDeQuestoes questao20 = new ListaDeQuestoes(R.drawable.questao20g,false,"Geografica","No croqui, a camada identificada com o número 2 corresponde _________ do planeta.","à crosta.","à litosfera.","à astenosfera.","ao manto.","ao manto.","");


        // add todas as questôes para List<ListaDeQuestoes>
        listaDeQuestoes.add(questao1);
        listaDeQuestoes.add(questao2);
        listaDeQuestoes.add(questao3);
        listaDeQuestoes.add(questao4);
        listaDeQuestoes.add(questao5);
        listaDeQuestoes.add(questao6);
        listaDeQuestoes.add(questao7);
        listaDeQuestoes.add(questao8);
        listaDeQuestoes.add(questao9);
        listaDeQuestoes.add(questao10);
        listaDeQuestoes.add(questao11);
        listaDeQuestoes.add(questao12);
        listaDeQuestoes.add(questao13);
        listaDeQuestoes.add(questao14);
        listaDeQuestoes.add(questao15);
        listaDeQuestoes.add(questao16);
        listaDeQuestoes.add(questao17);
        listaDeQuestoes.add(questao18);
        listaDeQuestoes.add(questao19);
        listaDeQuestoes.add(questao20);

        return listaDeQuestoes;
    }
    private static List<ListaDeQuestoes> questoesTodas(){
        List<ListaDeQuestoes> listaDeQuestoes = new ArrayList<>();

        listaDeQuestoes.addAll(questoesDeGeografia());
        listaDeQuestoes.addAll(questoesDeQuimica());
        listaDeQuestoes.addAll(questoesDeMatematica());
        listaDeQuestoes.addAll(questoesDePortugues());

        return listaDeQuestoes;
    }
    public static List<ListaDeQuestoes> getQuestoes(String selecionarMaterias){
        switch (selecionarMaterias){
            case "portugues":
                return questoesDePortugues();
            case "matematica":
                return questoesDeMatematica();
            case "quimica":
                return questoesDeQuimica();
            case "geografia":
                return questoesDeGeografia();
            default:
                return questoesTodas();
        }
    }
}
